### ISSUE TITLE
Suggestion: Move widget into a more generic subfolder

### ISSUE THREAD

**Issue by roemhildtg** [jebu75/cmv-layer-swapper#2]
It would be more convenient if your widget was in a higher directory. We're using git submodules to keep track of different projects, and the path to your widget becomes something like:

`viewer/js/gis/dijit/jebu75/viewer/js/gis/dijit/LayerSwapper.js`

**Comment by jebu75** [comment]
Great point, I’ll get that updated.  This was one of my first widgets and I wasn’t clear on how to structure a contributed widget.  Seems like placing in the root directory would make sense so your path would end up:
viewer/js/gis/dijit/jebu75/LayerSwapper.js

Agree?

I’ll talk it over with the CMV team as well.  This might be something we want to address in the guidelines/docs for user contributed widgets.

Thanks!

**Comment by jebu75** [comment]
@roemhildtg please take a look at my latest commit in the develop branch and let me know if this would work for you.

Moved LayerSwapper into a 'dijit' directory in the project root.  I think this will give you a directory structure like:
`viewer/js/gis/dijit/jebu75/dijit/LayerSwapper.js`

I realize it's a bit redundant but I didn't want the LayerSwapper files in the project root with other project files.

**Comment by jebu75** [comment]
https://github.com/jebu75/cmv-layer-swapper/pull/3 created

**Comment by roemhildtg** [comment]
I took a look at the branch and I think that's what I was going for. I know some of the other contributers are doing a similar structure for their cmv widgets and I think I'll adopt the same pattern for mine.
